[install]
style_name = "concordat"
vocab = "concordat"
min_alert_level = "warning"

[[install.post_sync_steps]]
action = "update-tengo-map"
type = "true"
source = ".config/common-acronyms"
dest = ".vale/styles/config/scripts/AcronymsFirstUse.tengo"
